@echo off
echo === JODHUR Full Render Pipeline ===
echo.
echo Rendering S1_Lun_savon-beldi_tiktok...
npx remotion render U1-FlashHook "out/S1_Lun_savon-beldi_tiktok.mp4" --props="renders/props/S1_Lun_savon-beldi_tiktok.json"
echo.
echo Rendering S1_Mar_savon-beldi_ig...
npx remotion render U3-StorySlide "out/S1_Mar_savon-beldi_ig.mp4" --props="renders/props/S1_Mar_savon-beldi_ig.json"
echo.
echo Rendering S1_Mer_savon-beldi_fb...
npx remotion render U1-FlashHook "out/S1_Mer_savon-beldi_fb.mp4" --props="renders/props/S1_Mer_savon-beldi_fb.json"
echo.
echo Rendering S1_Jeu_ghassoul_tiktok...
npx remotion render U1-FlashHook "out/S1_Jeu_ghassoul_tiktok.mp4" --props="renders/props/S1_Jeu_ghassoul_tiktok.json"
echo.
echo Rendering S1_Ven_ghassoul_ig...
npx remotion render U3-StorySlide "out/S1_Ven_ghassoul_ig.mp4" --props="renders/props/S1_Ven_ghassoul_ig.json"
echo.
echo Rendering S1_Sam_kit-hammam_tiktok...
npx remotion render U1-FlashHook "out/S1_Sam_kit-hammam_tiktok.mp4" --props="renders/props/S1_Sam_kit-hammam_tiktok.json"
echo.
echo Rendering S2_Lun_huile-d-argan_tiktok...
npx remotion render U1-FlashHook "out/S2_Lun_huile-d-argan_tiktok.mp4" --props="renders/props/S2_Lun_huile-d-argan_tiktok.json"
echo.
echo Rendering S2_Mar_huile-d-argan_ig...
npx remotion render U3-StorySlide "out/S2_Mar_huile-d-argan_ig.mp4" --props="renders/props/S2_Mar_huile-d-argan_ig.json"
echo.
echo Rendering S2_Mer_huile-d-argan_tiktok...
npx remotion render U1-FlashHook "out/S2_Mer_huile-d-argan_tiktok.mp4" --props="renders/props/S2_Mer_huile-d-argan_tiktok.json"
echo.
echo Rendering S2_Jeu_eau-de-rose_tiktok...
npx remotion render U1-FlashHook "out/S2_Jeu_eau-de-rose_tiktok.mp4" --props="renders/props/S2_Jeu_eau-de-rose_tiktok.json"
echo.
echo Rendering S2_Ven_eau-de-rose_ig...
npx remotion render U2-TutoPunch "out/S2_Ven_eau-de-rose_ig.mp4" --props="renders/props/S2_Ven_eau-de-rose_ig.json"
echo.
echo Rendering S2_Sam_pack-argan-+-rose_tiktok...
npx remotion render U1-FlashHook "out/S2_Sam_pack-argan-+-rose_tiktok.mp4" --props="renders/props/S2_Sam_pack-argan-+-rose_tiktok.json"
echo.
echo Rendering S3_Lun_huile-de-nigelle_tiktok...
npx remotion render U1-FlashHook "out/S3_Lun_huile-de-nigelle_tiktok.mp4" --props="renders/props/S3_Lun_huile-de-nigelle_tiktok.json"
echo.
echo Rendering S3_Mar_huile-de-nigelle_ig...
npx remotion render U3-StorySlide "out/S3_Mar_huile-de-nigelle_ig.mp4" --props="renders/props/S3_Mar_huile-de-nigelle_ig.json"
echo.
echo Rendering S3_Mer_eau-de-fleur-d-oranger_fb...
npx remotion render U1-FlashHook "out/S3_Mer_eau-de-fleur-d-oranger_fb.mp4" --props="renders/props/S3_Mer_eau-de-fleur-d-oranger_fb.json"
echo.
echo Rendering S3_Jeu_huile-de-ricin_tiktok...
npx remotion render U1-FlashHook "out/S3_Jeu_huile-de-ricin_tiktok.mp4" --props="renders/props/S3_Jeu_huile-de-ricin_tiktok.json"
echo.
echo Rendering S3_Ven_huile-de-ricin_ig...
npx remotion render U2-TutoPunch "out/S3_Ven_huile-de-ricin_ig.mp4" --props="renders/props/S3_Ven_huile-de-ricin_ig.json"
echo.
echo Rendering S3_Sam_trio-sanouj_tiktok...
npx remotion render U1-FlashHook "out/S3_Sam_trio-sanouj_tiktok.mp4" --props="renders/props/S3_Sam_trio-sanouj_tiktok.json"
echo.
echo Rendering S4_Lun_kit-hammam_ig...
npx remotion render U3-StorySlide "out/S4_Lun_kit-hammam_ig.mp4" --props="renders/props/S4_Lun_kit-hammam_ig.json"
echo.
echo Rendering S4_Mar_he-lavande_tiktok...
npx remotion render U1-FlashHook "out/S4_Mar_he-lavande_tiktok.mp4" --props="renders/props/S4_Mar_he-lavande_tiktok.json"
echo.
echo Rendering S4_Mer_he-lavande_tiktok...
npx remotion render U1-FlashHook "out/S4_Mer_he-lavande_tiktok.mp4" --props="renders/props/S4_Mer_he-lavande_tiktok.json"
echo.
echo Rendering S4_Jeu_gamme-compl-te_ig...
npx remotion render U3-StorySlide "out/S4_Jeu_gamme-compl-te_ig.mp4" --props="renders/props/S4_Jeu_gamme-compl-te_ig.json"
echo.
echo Rendering S4_Ven_eaux-florales_tiktok...
npx remotion render U1-FlashHook "out/S4_Ven_eaux-florales_tiktok.mp4" --props="renders/props/S4_Ven_eaux-florales_tiktok.json"
echo.
echo Rendering S4_Sam_coffret-routine_tiktok...
npx remotion render U1-FlashHook "out/S4_Sam_coffret-routine_tiktok.mp4" --props="renders/props/S4_Sam_coffret-routine_tiktok.json"
echo.
echo Rendering S5_Lun_huile-d-argan_ig...
npx remotion render U3-StorySlide "out/S5_Lun_huile-d-argan_ig.mp4" --props="renders/props/S5_Lun_huile-d-argan_ig.json"
echo.
echo Rendering S5_Mar_ghassoul_tiktok...
npx remotion render U2-TutoPunch "out/S5_Mar_ghassoul_tiktok.mp4" --props="renders/props/S5_Mar_ghassoul_tiktok.json"
echo.
echo Rendering S5_Mer_gamme-compl-te_fb...
npx remotion render U1-FlashHook "out/S5_Mer_gamme-compl-te_fb.mp4" --props="renders/props/S5_Mer_gamme-compl-te_fb.json"
echo.
echo Rendering S5_Jeu_huile-de-ricin_ig...
npx remotion render U2-TutoPunch "out/S5_Jeu_huile-de-ricin_ig.mp4" --props="renders/props/S5_Jeu_huile-de-ricin_ig.json"
echo.
echo Rendering S5_Ven_plantes-s-ch-es_tiktok...
npx remotion render U1-FlashHook "out/S5_Ven_plantes-s-ch-es_tiktok.mp4" --props="renders/props/S5_Ven_plantes-s-ch-es_tiktok.json"
echo.
echo Rendering S5_Sam_pack-anti-chute_tiktok...
npx remotion render U1-FlashHook "out/S5_Sam_pack-anti-chute_tiktok.mp4" --props="renders/props/S5_Sam_pack-anti-chute_tiktok.json"
echo.
echo Rendering S6_Lun_gamme-compl-te_ig...
npx remotion render U3-StorySlide "out/S6_Lun_gamme-compl-te_ig.mp4" --props="renders/props/S6_Lun_gamme-compl-te_ig.json"
echo.
echo Rendering S6_Mar_savon-beldi_tiktok...
npx remotion render U1-FlashHook "out/S6_Mar_savon-beldi_tiktok.mp4" --props="renders/props/S6_Mar_savon-beldi_tiktok.json"
echo.
echo Rendering S6_Mer_coop-rative_tiktok...
npx remotion render U1-FlashHook "out/S6_Mer_coop-rative_tiktok.mp4" --props="renders/props/S6_Mer_coop-rative_tiktok.json"
echo.
echo Rendering S6_Jeu_huiles-visage_ig...
npx remotion render U3-StorySlide "out/S6_Jeu_huiles-visage_ig.mp4" --props="renders/props/S6_Jeu_huiles-visage_ig.json"
echo.
echo Rendering S6_Ven_huile-figue-de-barbarie_tiktok...
npx remotion render U1-FlashHook "out/S6_Ven_huile-figue-de-barbarie_tiktok.mp4" --props="renders/props/S6_Ven_huile-figue-de-barbarie_tiktok.json"
echo.
echo Rendering S6_Sam_pack-clat-visage_tiktok...
npx remotion render U1-FlashHook "out/S6_Sam_pack-clat-visage_tiktok.mp4" --props="renders/props/S6_Sam_pack-clat-visage_tiktok.json"
echo.
echo Rendering S7_Lun_gamme-compl-te_tiktok...
npx remotion render U1-FlashHook "out/S7_Lun_gamme-compl-te_tiktok.mp4" --props="renders/props/S7_Lun_gamme-compl-te_tiktok.json"
echo.
echo Rendering S7_Mar_coffret-h-ritage_ig...
npx remotion render U3-StorySlide "out/S7_Mar_coffret-h-ritage_ig.mp4" --props="renders/props/S7_Mar_coffret-h-ritage_ig.json"
echo.
echo Rendering S7_Mer_leila-chatbot_fb...
npx remotion render U2-TutoPunch "out/S7_Mer_leila-chatbot_fb.mp4" --props="renders/props/S7_Mer_leila-chatbot_fb.json"
echo.
echo Rendering S7_Jeu_gamme-compl-te_tiktok...
npx remotion render U1-FlashHook "out/S7_Jeu_gamme-compl-te_tiktok.mp4" --props="renders/props/S7_Jeu_gamme-compl-te_tiktok.json"
echo.
echo Rendering S7_Ven_impact-social_fb...
npx remotion render U1-FlashHook "out/S7_Ven_impact-social_fb.mp4" --props="renders/props/S7_Ven_impact-social_fb.json"
echo.
echo Rendering S7_Sam_code-heritage25_tiktok...
npx remotion render U1-FlashHook "out/S7_Sam_code-heritage25_tiktok.mp4" --props="renders/props/S7_Sam_code-heritage25_tiktok.json"
echo.
echo Rendering S8_Lun_gamme-compl-te_ig...
npx remotion render U3-StorySlide "out/S8_Lun_gamme-compl-te_ig.mp4" --props="renders/props/S8_Lun_gamme-compl-te_ig.json"
echo.
echo Rendering S8_Mar_gamme-compl-te_tiktok...
npx remotion render U1-FlashHook "out/S8_Mar_gamme-compl-te_tiktok.mp4" --props="renders/props/S8_Mar_gamme-compl-te_tiktok.json"
echo.
echo Rendering S8_Mer_gamme-compl-te_tiktok...
npx remotion render U1-FlashHook "out/S8_Mer_gamme-compl-te_tiktok.mp4" --props="renders/props/S8_Mer_gamme-compl-te_tiktok.json"
echo.
echo Rendering S8_Jeu_box-vip_tiktok...
npx remotion render U1-FlashHook "out/S8_Jeu_box-vip_tiktok.mp4" --props="renders/props/S8_Jeu_box-vip_tiktok.json"
echo.
echo Rendering S8_Ven_gamme-compl-te_ig...
npx remotion render U1-FlashHook "out/S8_Ven_gamme-compl-te_ig.mp4" --props="renders/props/S8_Ven_gamme-compl-te_ig.json"
echo.
echo Rendering S8_Sam_code-jodhur30_tiktok...
npx remotion render U1-FlashHook "out/S8_Sam_code-jodhur30_tiktok.mp4" --props="renders/props/S8_Sam_code-jodhur30_tiktok.json"
echo.

echo.
echo === Tous les renders terminés ! ===
pause